---
# AWS Inventory for LAMP Stack

all:
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ lookup('env', 'AWS_SSH_KEY_FILE') | default('~/.ssh/aws-key.pem') }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    domain_name: testerlab.com
    environment: aws

  children:
    webservers:
      hosts:
        web1:
          ansible_host: "{{ hostvars['localhost']['web1_public_ip'] | default('') }}"
        web2:
          ansible_host: "{{ hostvars['localhost']['web2_public_ip'] | default('') }}"
      vars:
        ansible_user: ec2-user
        
    dbservers:
      hosts:
        db1:
          ansible_host: "{{ hostvars['localhost']['db1_endpoint'] | default('') }}"
        db2:
          ansible_host: "{{ hostvars['localhost']['db2_endpoint'] | default('') }}"
          
    loadbalancers:
      hosts:
        alb:
          ansible_host: "{{ hostvars['localhost']['alb_dns_name'] | default('') }}"
          
    efs:
      hosts:
        efs1:
          ansible_host: "{{ hostvars['localhost']['efs_dns_name'] | default('') }}"
          
    localhost:
      hosts:
        localhost:
          ansible_connection: local
